name: "Equicrew Frontend"
version: "2024.12.0-eq1"
slug: eq-frontend
description: "Custom Equicrew Home Assistant Frontend based on Home Assistant 2024.12"
url: https://github.com/behindvillager/eq-frontend
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
image: ghcr.io/behindvillager/eq-frontend-{arch}
